apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f apigateway-pattern.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: boss
  name: boss
spec:
  replicas: 2
  strategy: {
    type: RollingUpdate
  }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f apigateway-pattern.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: boss
    spec:
      containers:
      - image: boss_$(Build.BuildId)
        name: boss
        imagePullPolicy: Never # can use local image in docker desktop
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /location
            port: 3000
            httpHeaders:
              - name: Host
                value: KubernetesLivenessProbe
          initialDelaySeconds: 5
status: {}
