apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f apigateway-pattern.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: boss
  name: boss
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 3000
  selector:
    io.kompose.service: boss