apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f apigateway-pattern.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: deadlines
  name: deadlines
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f apigateway-pattern.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: deadlines
    spec:
      containers:
      - image: deadlines
        imagePullPolicy: Never # can use local image in docker desktop
        name: deadlines
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
