apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f apigateway-pattern.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: meetings
  name: meetings
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f apigateway-pattern.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: meetings
    spec:
      containers:
      - image: meetings
        name: meetings
        imagePullPolicy: Never # can use local image in docker desktop
        ports:
        - containerPort: 1337
        resources: {}
      restartPolicy: Always
status: {}
