apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
    type: LoadBalancer
    ports:
    - port: 6379
      targetPort: 6379
    selector:
      io.kompose.service: redis