apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f apigateway-pattern.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: socketserver
  name: socketserver
spec:
  ports:
  - name: "8787"
    port: 8787
    targetPort: 8787
  selector:
    io.kompose.service: socketserver
status:
  loadBalancer: {}
